# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files

  - repo: local
    hooks:
      - id: uv-check
        name: Check package dependencies
        entry: uv sync --locked
        language: system
        pass_filenames: false

      - id: ruff-format
        name: ruff format
        entry: uv run ruff format
        language: system
        types_or: [ python, pyi ]

      - id: ruff-check
        name: ruff check
        entry: uv run ruff check --fix
        language: system
        types_or: [ python, pyi ]

      - id: mypy
        name: Validate types with MyPy
        entry: uv run mypy app
        language: system
        types: [ python ]
        pass_filenames: false
